//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCollection.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomProject
    {
        public System.Guid CustomProjectId { get; set; }
        public string No { get; set; }
        public System.Guid ProjectPlanId { get; set; }
        public System.DateTime SendingDate { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string Title { get; set; }
        public string CourseAmount { get; set; }
        public string lecturer { get; set; }
        public string LecturerJob { get; set; }
        public string CourseSource { get; set; }
        public string Category { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> Signer { get; set; }
        public Nullable<System.Guid> Operator { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string ReceiveNote { get; set; }
        public string OperationNote { get; set; }
        public Nullable<System.Guid> Publisher { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.Guid> PublishCheck { get; set; }
        public string PublishNote { get; set; }
        public Nullable<System.Guid> Checker { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<System.Guid> CategoryCheck { get; set; }
        public string CheckNote { get; set; }
        public System.Guid Progress { get; set; }
        public System.Guid PublishNeeds { get; set; }
        public string ExtraNote { get; set; }
    
        public virtual data_dictionary data_dictionary { get; set; }
        public virtual ProjectPlan ProjectPlan { get; set; }
        public virtual user_info user_info { get; set; }
        public virtual user_info user_info1 { get; set; }
        public virtual user_info user_info2 { get; set; }
        public virtual user_info user_info3 { get; set; }
    }
}
