//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCollection.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectPlan()
        {
            this.CustomProject = new HashSet<CustomProject>();
        }
    
        public System.Guid ProjectPlanId { get; set; }
        public string ProjectPlanNo { get; set; }
        public string title { get; set; }
        public System.Guid ProjectPlanTypeId { get; set; }
        public System.DateTime MakingDate { get; set; }
        public System.DateTime PlanDate { get; set; }
        public Nullable<System.DateTime> ExecuteDate { get; set; }
        public System.Guid progress { get; set; }
        public System.Guid CreatorId { get; set; }
        public string note { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public string Lecturer { get; set; }
        public Nullable<System.DateTime> LeadDate { get; set; }
        public Nullable<decimal> CourseCount { get; set; }
        public Nullable<int> Price { get; set; }
        public string Source { get; set; }
        public string Category { get; set; }
        public Nullable<System.Guid> RecordingPersonInCharge { get; set; }
        public Nullable<System.DateTime> RecordingDate { get; set; }
        public string RecordingPlace { get; set; }
        public Nullable<bool> RecordingScriptHolder { get; set; }
        public Nullable<int> RecordingLecture { get; set; }
        public Nullable<System.Guid> RecordingProgress { get; set; }
        public string RecordingNote { get; set; }
        public Nullable<System.DateTime> FileDeliverDate { get; set; }
        public string RecordingFile { get; set; }
        public string LecturerJob { get; set; }
        public string ExtraNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomProject> CustomProject { get; set; }
    }
}
