//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCollection.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempCourse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TempCourse()
        {
            this.TempOrder = new HashSet<TempOrder>();
        }
    
        public string CourseId { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string lecturer_name { get; set; }
        public string lecturer_post { get; set; }
        public string GroupName { get; set; }
        public string type { get; set; }
        public string TempletType { get; set; }
        public string InternalCategoryTop { get; set; }
        public string InternalCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempOrder> TempOrder { get; set; }
    }
}
