//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCollection.DAL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_dictionary
    {
        public data_dictionary()
        {
            this.Projects = new HashSet<Project>();
            this.Projects1 = new HashSet<Project>();
            this.Projects2 = new HashSet<Project>();
            this.Projects3 = new HashSet<Project>();
            this.Projects4 = new HashSet<Project>();
            this.Projects5 = new HashSet<Project>();
            this.Projects6 = new HashSet<Project>();
            this.Projects7 = new HashSet<Project>();
            this.Projects8 = new HashSet<Project>();
            this.Projects9 = new HashSet<Project>();
            this.Projects10 = new HashSet<Project>();
            this.Projects11 = new HashSet<Project>();
            this.Projects12 = new HashSet<Project>();
            this.Projects13 = new HashSet<Project>();
            this.Projects14 = new HashSet<Project>();
            this.Projects15 = new HashSet<Project>();
            this.Projects16 = new HashSet<Project>();
            this.Projects17 = new HashSet<Project>();
            this.Projects18 = new HashSet<Project>();
            this.Projects19 = new HashSet<Project>();
            this.Projects20 = new HashSet<Project>();
            this.Projects21 = new HashSet<Project>();
            this.Projects22 = new HashSet<Project>();
            this.Projects23 = new HashSet<Project>();
            this.Projects24 = new HashSet<Project>();
            this.Projects25 = new HashSet<Project>();
            this.Projects26 = new HashSet<Project>();
            this.Projects27 = new HashSet<Project>();
            this.Projects28 = new HashSet<Project>();
            this.Projects29 = new HashSet<Project>();
            this.Projects30 = new HashSet<Project>();
            this.Projects31 = new HashSet<Project>();
            this.Projects32 = new HashSet<Project>();
            this.Projects33 = new HashSet<Project>();
            this.Projects34 = new HashSet<Project>();
            this.Projects35 = new HashSet<Project>();
            this.Projects36 = new HashSet<Project>();
            this.Projects37 = new HashSet<Project>();
            this.Projects38 = new HashSet<Project>();
            this.Projects39 = new HashSet<Project>();
            this.Projects40 = new HashSet<Project>();
            this.Projects41 = new HashSet<Project>();
            this.Projects42 = new HashSet<Project>();
            this.Projects43 = new HashSet<Project>();
            this.Projects44 = new HashSet<Project>();
            this.Projects45 = new HashSet<Project>();
            this.Projects46 = new HashSet<Project>();
            this.Projects47 = new HashSet<Project>();
            this.Projects48 = new HashSet<Project>();
            this.Projects49 = new HashSet<Project>();
            this.Projects50 = new HashSet<Project>();
            this.Projects51 = new HashSet<Project>();
            this.Projects52 = new HashSet<Project>();
            this.ProjectPlans = new HashSet<ProjectPlan>();
            this.ProjectPlans1 = new HashSet<ProjectPlan>();
            this.ProjectPlans2 = new HashSet<ProjectPlan>();
            this.user_info = new HashSet<user_info>();
        }
    
        public System.Guid dictionary_identity { get; set; }
        public string category { get; set; }
        public string category_text { get; set; }
        public string text { get; set; }
        public string value { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Project> Projects1 { get; set; }
        public virtual ICollection<Project> Projects2 { get; set; }
        public virtual ICollection<Project> Projects3 { get; set; }
        public virtual ICollection<Project> Projects4 { get; set; }
        public virtual ICollection<Project> Projects5 { get; set; }
        public virtual ICollection<Project> Projects6 { get; set; }
        public virtual ICollection<Project> Projects7 { get; set; }
        public virtual ICollection<Project> Projects8 { get; set; }
        public virtual ICollection<Project> Projects9 { get; set; }
        public virtual ICollection<Project> Projects10 { get; set; }
        public virtual ICollection<Project> Projects11 { get; set; }
        public virtual ICollection<Project> Projects12 { get; set; }
        public virtual ICollection<Project> Projects13 { get; set; }
        public virtual ICollection<Project> Projects14 { get; set; }
        public virtual ICollection<Project> Projects15 { get; set; }
        public virtual ICollection<Project> Projects16 { get; set; }
        public virtual ICollection<Project> Projects17 { get; set; }
        public virtual ICollection<Project> Projects18 { get; set; }
        public virtual ICollection<Project> Projects19 { get; set; }
        public virtual ICollection<Project> Projects20 { get; set; }
        public virtual ICollection<Project> Projects21 { get; set; }
        public virtual ICollection<Project> Projects22 { get; set; }
        public virtual ICollection<Project> Projects23 { get; set; }
        public virtual ICollection<Project> Projects24 { get; set; }
        public virtual ICollection<Project> Projects25 { get; set; }
        public virtual ICollection<Project> Projects26 { get; set; }
        public virtual ICollection<Project> Projects27 { get; set; }
        public virtual ICollection<Project> Projects28 { get; set; }
        public virtual ICollection<Project> Projects29 { get; set; }
        public virtual ICollection<Project> Projects30 { get; set; }
        public virtual ICollection<Project> Projects31 { get; set; }
        public virtual ICollection<Project> Projects32 { get; set; }
        public virtual ICollection<Project> Projects33 { get; set; }
        public virtual ICollection<Project> Projects34 { get; set; }
        public virtual ICollection<Project> Projects35 { get; set; }
        public virtual ICollection<Project> Projects36 { get; set; }
        public virtual ICollection<Project> Projects37 { get; set; }
        public virtual ICollection<Project> Projects38 { get; set; }
        public virtual ICollection<Project> Projects39 { get; set; }
        public virtual ICollection<Project> Projects40 { get; set; }
        public virtual ICollection<Project> Projects41 { get; set; }
        public virtual ICollection<Project> Projects42 { get; set; }
        public virtual ICollection<Project> Projects43 { get; set; }
        public virtual ICollection<Project> Projects44 { get; set; }
        public virtual ICollection<Project> Projects45 { get; set; }
        public virtual ICollection<Project> Projects46 { get; set; }
        public virtual ICollection<Project> Projects47 { get; set; }
        public virtual ICollection<Project> Projects48 { get; set; }
        public virtual ICollection<Project> Projects49 { get; set; }
        public virtual ICollection<Project> Projects50 { get; set; }
        public virtual ICollection<Project> Projects51 { get; set; }
        public virtual ICollection<Project> Projects52 { get; set; }
        public virtual ICollection<ProjectPlan> ProjectPlans { get; set; }
        public virtual ICollection<ProjectPlan> ProjectPlans1 { get; set; }
        public virtual ICollection<ProjectPlan> ProjectPlans2 { get; set; }
        public virtual ICollection<user_info> user_info { get; set; }
    }
}
