//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCollection.DAL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTimeLimit
    {
        public System.Guid ProjectTimeLimitId { get; set; }
        public System.Guid ProjectId { get; set; }
        public Nullable<System.DateTime> TimeSpanCapture { get; set; }
        public Nullable<System.DateTime> TimeSpanCaptureCheck { get; set; }
        public Nullable<System.DateTime> TimeSpanExecution { get; set; }
        public Nullable<System.DateTime> TimeSpanShorthand { get; set; }
        public Nullable<System.DateTime> TimeSpanContent { get; set; }
        public Nullable<System.DateTime> TimeSpanProduction { get; set; }
        public Nullable<System.DateTime> TimeSpanPublish { get; set; }
        public Nullable<System.DateTime> TimeSpanCheck { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
