//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCollection.DAL.EntityDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectCollectionEntities : DbContext
    {
        public ProjectCollectionEntities()
            : base("name=ProjectCollectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<data_dictionary> data_dictionary { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<ProjectPlan> ProjectPlans { get; set; }
        public DbSet<ProjectPlanRecord> ProjectPlanRecords { get; set; }
        public DbSet<ProjectRecord> ProjectRecords { get; set; }
        public DbSet<ProjectTimeLimit> ProjectTimeLimits { get; set; }
        public DbSet<user_authority> user_authority { get; set; }
        public DbSet<user_info> user_info { get; set; }
        public DbSet<WorkSchedual> WorkScheduals { get; set; }
    }
}
