//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCollection.DAL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_authority
    {
        public System.Guid authority_identity { get; set; }
        public string url { get; set; }
        public string authority { get; set; }
    }
}
