//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCollection.DAL.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_info
    {
        public user_info()
        {
            this.Projects = new HashSet<Project>();
            this.Projects1 = new HashSet<Project>();
            this.Projects2 = new HashSet<Project>();
            this.Projects3 = new HashSet<Project>();
            this.Projects4 = new HashSet<Project>();
            this.Projects5 = new HashSet<Project>();
            this.Projects6 = new HashSet<Project>();
            this.Projects7 = new HashSet<Project>();
            this.Projects8 = new HashSet<Project>();
            this.Projects9 = new HashSet<Project>();
            this.Projects10 = new HashSet<Project>();
            this.Projects11 = new HashSet<Project>();
            this.Projects12 = new HashSet<Project>();
            this.Projects13 = new HashSet<Project>();
            this.ProjectPlans = new HashSet<ProjectPlan>();
            this.ProjectPlans1 = new HashSet<ProjectPlan>();
            this.ProjectPlans2 = new HashSet<ProjectPlan>();
            this.data_dictionary = new HashSet<data_dictionary>();
        }
    
        public System.Guid user_identity { get; set; }
        public string login_name { get; set; }
        public string password { get; set; }
        public string real_name { get; set; }
        public string Email_address { get; set; }
        public Nullable<System.Guid> role_identity { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Project> Projects1 { get; set; }
        public virtual ICollection<Project> Projects2 { get; set; }
        public virtual ICollection<Project> Projects3 { get; set; }
        public virtual ICollection<Project> Projects4 { get; set; }
        public virtual ICollection<Project> Projects5 { get; set; }
        public virtual ICollection<Project> Projects6 { get; set; }
        public virtual ICollection<Project> Projects7 { get; set; }
        public virtual ICollection<Project> Projects8 { get; set; }
        public virtual ICollection<Project> Projects9 { get; set; }
        public virtual ICollection<Project> Projects10 { get; set; }
        public virtual ICollection<Project> Projects11 { get; set; }
        public virtual ICollection<Project> Projects12 { get; set; }
        public virtual ICollection<Project> Projects13 { get; set; }
        public virtual ICollection<ProjectPlan> ProjectPlans { get; set; }
        public virtual ICollection<ProjectPlan> ProjectPlans1 { get; set; }
        public virtual ICollection<ProjectPlan> ProjectPlans2 { get; set; }
        public virtual ICollection<data_dictionary> data_dictionary { get; set; }
    }
}
